spring:
  application:
    name: demoapp
  zipkin:
    enabled: false

logging:
  level:
    root: info

server:
  port: 8080

keystore:
  #file:  ${KEYSTORE_LOCATION}
  file:  "classpath:keystore-dev.jks"
  password: "123456"

file:
  path: "classpath:demo.sign-m.pdf"


client:
  issuer_uri: https://oidc.sandbox.bankid.cz/
  client_id: place_your_client_id_from_dev_portal
  client_secret: place_your_client_secret_from_dev_portal
  redirect_uri: http://localhost:8080/callback
  client_scopes: "openid profile.name profile.email profile.phonenumber"
